//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Entities.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public int ID { get; set; }
        public string TokenID { get; set; }
        public string Subject { get; set; }
        public int ClientID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string ProtectedTicket { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
